services:
  - type: web
    name: fend-backend
    env: python
    buildCommand: pip install -r requeriments.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHONPATH
        value: src
